name: Build

on:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use latest ESR version of Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest-esr

      - run: npm install
      - run: npm run build
